### ISSUE TITLE
Hash inconsistency between calling db$finish() and knitting the html

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/laminr#104]
Upon knitting the html and no changes to the source code, we don't want throw an error and require bumping the version.

This is likely an issue within lamindb where it does this because it assumes re-execution will change the source code hash.

I'll look into this.

**Comment by falexwolf** [comment]
Probably not. Probably @rcannood made a small change to the source code between knitting and calling `db$finish()`

The `.Rmd` is currently categorized as a "script" because Robrecht used lamindb 0.76.16 and I only fixed this in lamindb 0.77
<img width="483" alt="image" src="https://github.com/user-attachments/assets/4db42c5c-8c96-4bf8-889f-10fccdc16d2d">

**Comment by falexwolf** [comment]
Never calling `db$finish()` interactively would solve the problem.

- https://github.com/laminlabs/laminr/issues/110

**Comment by lazappi** [comment]
I think this is fixed by #120

**Comment by falexwolf** [comment]
I also think so!
