### ISSUE TITLE
Add an example for slicing census / tiledbsoma

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/laminr#108]
"Subsetting to all T cells."

This means querying this here: https://lamin.ai/laminlabs/cellxgene/artifact/FYMewVq5twKMDXVy0001

Similar to what we have here: https://docs.lamin.ai/cellxgene#slice-a-concatenated-array

Use: https://chanzuckerberg.github.io/cellxgene-census/r/index.html#usage

This will become more intuitive when the following is done:

- https://github.com/laminlabs/cellxgene-lamin/issues/109

**Comment by lazappi** [comment]
Done in #117
