### ISSUE TITLE
Enable to omit passing `path = ...` within `db$track()`

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/laminr#115]
This is more important than I initially realized because it's related to the portability of the code.

People might rename the file or execute it in a different folder and then the code will fail.

I think by far the most common will be the RStudio case with `.Rmd` or `.qmd`. Hence, just solving it there is a big UX win.

Previous discussion:

- https://github.com/laminlabs/laminr/issues/76

**Comment by lazappi** [comment]
@falexwolf In Python do you use absolute paths, relative paths or just the file name?

**Comment by falexwolf** [comment]
Sorry for being soo late here 😔 

In Python, users can pass any of these and under-the-hood things will be resolved to absolute paths. For portability relative paths are always better.

**Comment by falexwolf** [comment]
It _might_ be that it's more robust if R dynamically finds an absolute path and passes that to Python

But if there is no ambiguity about working directory of R and Python session it won't matter

I don't have intuition on this right now

**Comment by lazappi** [comment]
Ok. At the moment it's a relative path but getting an absolute path should be easy so I could switch to that if it's better. I'm not sure if the working directories match either but I would guess **{reticulate}** tries to make that happen?

**Comment by lazappi** [comment]
This works after #120 so can probably close unless we want to switch to absolute paths.

**Comment by falexwolf** [comment]
Can close! 😄
