### ISSUE TITLE
Give better error message if record not found

### ISSUE THREAD

**Issue by lazappi** [laminlabs/laminr#44]
If possible with the API, give a different error if a request is successful but a record is not in the database, versus if a request fails completely.

**Comment by rcannood** [comment]
For instance, this is what we get from the API at the moment:

```r
> artifact <- db$Artifact$get("KBW89Mf7IGcekja2hADu")
Error in `private$process_response()`:
! list index out of range
```

I'd say this is up to the API to do better error handling to provide more descriptive error messages. 

For instance, in this case the API should be something like `Artifact "KBW89Mf7IGcekja2hADu" not found`.

We _could_ implement functionality to map the most common error messages returned by the API into something that is understandable from the perspective of an R user, but at this point it seems the API is simply returning whatever goes wrong inside of the Python code, so there is no knowing which error messages the API might return.

**Comment by falexwolf** [comment]
I agree. @fredericenard can comment how fast this can be done.

**Comment by fredericenard** [comment]
I did this [here](https://github.com/laminlabs/laminhub/pull/1517) for the get record endpoint.

**Comment by fredericenard** [comment]
@rcannood @lazappi it has been deployed in prod, you should now have a 404 error for non existing records.
