### ISSUE TITLE
Add progress to `Record$cache()` and `Record$load()`

### ISSUE THREAD

**Issue by lazappi** [laminlabs/laminr#45]
Getting objects is likely to be slow. It would be nice to see what is happening rather than just waiting.

**Comment by lazappi** [comment]
#58 does this for `Artifact$cache()` (for S3). I think for `Artifact$load()` this would require changes to R/Python **anndata** packages.

**Comment by rcannood** [comment]
I think the progress bar for load is simply the cache PB.

This feature was implemented in #58.

**Comment by lazappi** [comment]
Ok. I guess that works if the file isn't so big that actually reading it from disk takes ages.
